# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * account_plaid
# 
# Translators:
# Martin Trigaux <mat@odoo.com>, 2016
# grazziano <g.negocios@outlook.com.br>, 2016
# Mateus Lopes <mateus1@gmail.com>, 2016
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 9.saas~11e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-08-19 11:34+0000\n"
"PO-Revision-Date: 2016-08-19 11:34+0000\n"
"Last-Translator: Mateus Lopes <mateus1@gmail.com>, 2016\n"
"Language-Team: Portuguese (Brazil) (https://www.transifex.com/odoo/teams/41243/pt_BR/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: pt_BR\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_online_account_token
msgid "Access Token"
msgstr "Token de Acesso"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:72
#: code:addons/account_plaid/models/plaid.py:74
#: code:addons/account_plaid/models/plaid.py:89
#, python-format
msgid "An error has occurred while trying to connect to plaid service"
msgstr "Ocorreu um erro ao tentar conectar-se ao serviço Plaid"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:155
#, python-format
msgid "Error in synchronization"
msgstr "Erro em Sincronização"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:162
#, python-format
msgid "Error with Plaid.com"
msgstr "Erro em Plaid.com"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_account_journal
msgid "Journal"
msgstr "Diário"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_account_journal_onlinesync_config_plaid_account_id
msgid "Online Account"
msgstr "Conta Online"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_online_account_plaid_id
msgid "Plaid Account"
msgstr "Conta Plaid"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_account_config_settings_plaid_id
msgid "Plaid ID"
msgstr "ID do Plano"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_account_config_settings_plaid_secret
msgid "Plaid Secret"
msgstr "Segredo Plaid"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:156
#, python-format
msgid ""
"The synchronization of the journal %s with the plaid account %s has "
"failed.<br>The error message is :<br>%s"
msgstr ""
"A sincronização do diário %s com a conta Plaid %s falhou.<br>A mensagem de "
"erro é:<br> %s"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:163
#, python-format
msgid ""
"The synchronization with Plaid.com failed. Please check the error : <br> %s"
msgstr ""
"A sincronização com Plaid.com falhou. Por favor, cheque o erro : <br> %s"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:57
#, python-format
msgid ""
"You haven't configure your plaid account, please go to accounting/settings "
"to configure it"
msgstr ""
"Você não configurou sua conta Plaid, por favor, vá para "
"contabilidade/configurações para configurá-la"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_account_config_settings
msgid "account.config.settings"
msgstr "account.config.settings"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_account_journal_onlinesync_config
msgid "account.journal.onlinesync.config"
msgstr "account.journal.onlinesync.config"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_online_account
msgid "online.account"
msgstr ""

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_online_institution
msgid "online.institution"
msgstr "online.institution"
